
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fintech-redis-01
  labels:
    app: vpromq01
spec:
  selector:
    matchLabels:
      app: fintech-redis-01
  replicas: 1
  template:
    metadata:
      labels:
        app: fintech-redis-01
    spec:
      containers:
      - name: fintech-redis-01
        image: redis:7-alpine
        ports:
        - name: fintech-redis-01-port
          containerPort: 6379
