apiVersion: v1
kind: Service
metadata:
  name: fintech-redis-01
spec:
  ports:
  - port: 6379
    targetPort: fintech-redis-01-port
    protocol: TCP
  selector:
    app: fintech-redis-01
  type: ClusterIP
