
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  ports:
  - port: 8080
    targetPort: api-port
    protocol: TCP
  - port: 587
    targetPort: smtp-port
    protocol: TCP
  selector:
    app: fintech-api (must match label under the selector in the deployment file)
  type: LoadBalancer 
  #type: ClusterIp

