apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  ports:
  - name: http
    port: 8080
    targetPort: api-port
    protocol: TCP
  - name: smtp
    port: 587
    targetPort: smtp-port
    protocol: TCP
  selector:
    app: fintech-api
  type: LoadBalancer
