// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddWalletBalance(ctx context.Context, arg AddWalletBalanceParams) (Wallet, error)
	CreateRedeem(ctx context.Context, arg CreateRedeemParams) (Redeem, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVerifyEmail(ctx context.Context, arg CreateVerifyEmailParams) (VerifyEmail, error)
	CreateVoucher(ctx context.Context, arg CreateVoucherParams) (Voucher, error)
	CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error)
	DeleteRedeem(ctx context.Context, id int64) error
	DeleteVoucher(ctx context.Context, id int64) error
	GetRedeem(ctx context.Context, id int64) (Redeem, error)
	GetRedeemWithCode(ctx context.Context, code string) (Redeem, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetTransaction(ctx context.Context, id int64) (Transaction, error)
	GetUser(ctx context.Context, username string) (User, error)
	GetVoucher(ctx context.Context, id int64) (Voucher, error)
	GetVoucherWithCode(ctx context.Context, arg GetVoucherWithCodeParams) (Voucher, error)
	GetWallet(ctx context.Context, id int64) (Wallet, error)
	GetWalletbyOwner(ctx context.Context, owner string) (Wallet, error)
	ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error)
	ListVouchers(ctx context.Context, creatorUsername pgtype.Text) ([]Voucher, error)
	UpdateTransactionReceiverWallet(ctx context.Context, arg UpdateTransactionReceiverWalletParams) (Transaction, error)
	UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) (Transaction, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error)
	UpdateVerifyEmail(ctx context.Context, arg UpdateVerifyEmailParams) (VerifyEmail, error)
	UpdateVoucherStatus(ctx context.Context, arg UpdateVoucherStatusParams) (Voucher, error)
	UpdateVoucherUsedBy(ctx context.Context, arg UpdateVoucherUsedByParams) error
	UpdateWallet(ctx context.Context, arg UpdateWalletParams) (Wallet, error)
}

var _ Querier = (*Queries)(nil)
